/* ============================================================================
   resources/g1_korean_u2.js — 케이티처 자료층 · 1학년 1학기 국어 2단원 「받침이 있는 글자를 읽어요」
   2026-09-23 (자료층 3차, 베프). 표준 = resources/README.md · 꼴 = g1_korean_u1.js
   - 링크는 전부 웹 검색으로 실측한 것(온스쿨 1학년 국어 페이지·EBS 한글이 야호·울산 교육연구정보원 등). 지어낸 ID 0건.
   - ⚠️ 온스쿨 영상은 2015 교육과정 판이다 — 단원 번호·교과서 쪽수가 다르다(note에 적음).
   - 미확보 1자리: l09 — 검색 카드로 남긴다.
   - 살아 있는지는 사람이 재생해 본다(삭제·비공개는 실기기에서만 잡힌다).
   ============================================================================ */
(function () {
  window.KT_RESOURCES = window.KT_RESOURCES || {};
  var COMMON = [{"id": "kd_u2_home", "type": "kedu", "icon": "🏠", "title": "자기주도 — 2단원 차시 목록", "description": "학생이 혼자 푸는 케이에듀 국어 차시 목록.", "url": "/grade1/semester1/korean/index.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}, {"id": "lk_u2_onschool", "type": "link", "icon": "🔗", "title": "온스쿨 1학년 국어 — 차시별 영상 모음(교사용)", "description": "실천교육교사모임 온스쿨. 이 단원 영상 대부분의 출처(2015 판 단원·쪽수).", "url": "https://sites.google.com/view/onschool/1%ED%95%99%EB%85%84/1%ED%95%99%EB%85%84-%EA%B5%AD%EC%96%B4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}, {"id": "lk_ebs_yaho2", "type": "link", "icon": "🔗", "title": "EBS 한글이 야호 2 — 받침 글자 회차 모음", "description": "니은·리을 받침 등 받침 글자 회차를 골라 볼 수 있는 EBS 공식 페이지.", "url": "https://home.ebs.co.kr/yaho2/main", "source": "EBS", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover", "concept"]}, {"id": "lk_bojung_g1kor", "type": "link", "icon": "🔗", "title": "초등 기초학력 보정자료 — 1-1 국어", "description": "한글 미해득 학생용 보정 활동지 모음(경기). 받침·낱말 읽기 보충에.", "url": "https://sites.google.com/view/goebasenara/%ED%99%88/1%ED%95%99%EB%85%84-%EA%B5%AD%EC%96%B4%EB%82%98%EB%9D%BC/1-1-%EA%B5%AD%EC%96%B4-%EA%B0%80", "source": "경기 기초학력 보정자료", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["leveled_problem", "summary"]}];
  var R = {
    u2_l01: [
      {"id": "v_squirrel", "type": "video", "icon": "🎥", "title": "다람쥐에게 일어난 일 — 받침이 빠지면?", "description": "받침을 빠뜨린 글자 때문에 생긴 일. 받침이 왜 필요한지 여는 도입 영상.", "url": "https://www.youtube.com/watch?v=QuD0rM0rnwA", "video_id": "QuD0rM0rnwA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_ebs_mnol", "type": "video", "icon": "🎥", "title": "한글이 야호 — 받침 한글동화(곰·밤·눈·말…)", "description": "EBS 한글이 야호. ㅁ·ㄴ·ㅇ·ㄹ 받침 낱말이 이야기로 나와요.", "url": "https://www.youtube.com/watch?v=y6R9CJxLthQ", "video_id": "y6R9CJxLthQ", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"]},
      {"id": "kd_u2_l01_02", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 1~2차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l01_02.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb19", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 받침 글자", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/1_문법/g1_kor_tb_19_받침글자.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l02: [
      {"id": "v_song_struct", "type": "video", "icon": "🎥", "title": "글자의 짜임 노래(자음+모음, 글자+받침)", "description": "ㄱ~ㅎ 짜임을 노래로. 받침 단원 들어가기 전 몸 풀기.", "url": "https://www.youtube.com/watch?v=1gqJTk0_6aU", "video_id": "1gqJTk0_6aU", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"], "note": "2015 교육과정 판(4단원 글자를 만들어요) 영상 — 내용은 같아요"},
      {"id": "v_ebs_all", "type": "video", "icon": "🎥", "title": "한글이 야호 — 기본받침·쌍자음·이중모음 총 복습", "description": "EBS 한글이 야호 복습편. 단원 마무리·기초 다지기에.", "url": "https://www.youtube.com/watch?v=aSbbf_GOIMw", "video_id": "aSbbf_GOIMw", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "kd_u2_l01_02", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 1~2차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l01_02.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l03: [
      {"id": "v_find_bat", "type": "video", "icon": "🎥", "title": "글자에서 받침 찾아보기", "description": "받침 있는 글자와 없는 글자를 견주어 보는 교과서 활동 영상.", "url": "https://www.youtube.com/watch?v=7b6Z_23HPa0", "video_id": "7b6Z_23HPa0", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_smart_bat", "type": "video", "icon": "🎥", "title": "받침이 있는 글자의 짜임", "description": "자음자+모음자+받침 자리를 짚어 주는 짧은 설명 영상.", "url": "https://www.youtube.com/watch?v=Yy4PW-HU_q4", "video_id": "Yy4PW-HU_q4", "source": "스마트올(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "kd_u2_l03_04", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 3~4차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l03_04.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb19", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 받침 글자", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/1_문법/g1_kor_tb_19_받침글자.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l04: [
      {"id": "v_make_bat", "type": "video", "icon": "🎥", "title": "받침을 넣어 글자 만들어 보기", "description": "모음자 아래 받침을 넣어 새 글자를 만드는 교과서 활동 영상.", "url": "https://www.youtube.com/watch?v=-4l02jhwFYA", "video_id": "-4l02jhwFYA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_play_bat", "type": "video", "icon": "🎥", "title": "받침이 있는 글자 만들기 놀이", "description": "글자 카드로 받침 글자를 만드는 놀이 시범.", "url": "https://www.youtube.com/watch?v=HSHZ9NpTy-o", "video_id": "HSHZ9NpTy-o", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["offline_activity", "card_quiz"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_act_make", "type": "video", "icon": "🎥", "title": "받침이 있는 글자 만들기(국어활동)", "description": "국어활동 받침 글자 만들기 풀이 영상.", "url": "https://www.youtube.com/watch?v=rNzIMTm6_sM", "video_id": "rNzIMTm6_sM", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "offline_activity"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "kd_u2_l03_04", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 3~4차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l03_04.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l05: [
      {"id": "v_ebs_mnol", "type": "video", "icon": "🎥", "title": "한글이 야호 — 받침 한글동화(곰·밤·눈·말…)", "description": "EBS 한글이 야호. ㅁ·ㄴ·ㅇ·ㄹ 받침 낱말이 이야기로 나와요.", "url": "https://www.youtube.com/watch?v=y6R9CJxLthQ", "video_id": "y6R9CJxLthQ", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"]},
      {"id": "v_ebs_ng", "type": "video", "icon": "🎥", "title": "한글이 야호 — 한글동화(공·콩·창·병…)", "description": "EBS 한글이 야호. ㅇ 받침 낱말(공·콩·창·총·병)이 나오는 동화.", "url": "https://www.youtube.com/watch?v=xrT7mgEtwRY", "video_id": "xrT7mgEtwRY", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"]},
      {"id": "kd_u2_l05_07", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 5~7차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l05_07.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l06: [
      {"id": "v_ebs_b", "type": "video", "icon": "🎥", "title": "한글이 야호 — 한글동화(밥·집·탑·쌍둥이·짝짜꿍)", "description": "EBS 한글이 야호. ㅂ 받침 낱말과 쌍자음 낱말이 이어 나와요.", "url": "https://www.youtube.com/watch?v=IJ3I6Yay1rs", "video_id": "IJ3I6Yay1rs", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"]},
      {"id": "v_gl_game", "type": "video", "icon": "🎥", "title": "ㄱ·ㄹ 받침 글자 게임", "description": "ㄱ·ㄹ 받침 글자 맞히기 게임(상업 채널).", "url": "https://www.youtube.com/watch?v=aJXjFRJIBm4", "video_id": "aJXjFRJIBm4", "source": "키즈봄(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["card_quiz"]},
      {"id": "kd_u2_l05_07", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 5~7차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l05_07.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l07: [
      {"id": "v_act_fit", "type": "video", "icon": "🎥", "title": "알맞은 받침 찾아 쓰기", "description": "세 글자에 모두 들어가는 받침 찾기 등 국어활동 풀이.", "url": "https://www.youtube.com/watch?v=XkFfx56drNY", "video_id": "XkFfx56drNY", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "card_quiz"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_plas", "type": "video", "icon": "🎥", "title": "받침이 있는 글자와 낱말 읽기", "description": "배이스캠프(교육 공익 프로그램) 1학년 국어 영상.", "url": "https://www.youtube.com/watch?v=5pqJnc47Zk4", "video_id": "5pqJnc47Zk4", "source": "PLAS 배이스캠프", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "read_aloud"]},
      {"id": "kd_u2_l05_07", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 5~7차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l05_07.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l08: [
      {"id": "v_pose_song", "type": "video", "icon": "🎥", "title": "바른 자세로 듣고 말해요(노래)", "description": "듣고 말하는 자세를 노래로 익혀요.", "url": "https://www.youtube.com/watch?v=tUUZK5Wzhpw", "video_id": "tUUZK5Wzhpw", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"], "note": "2015 교육과정 판(1단원 바른 자세로 읽고 쓰기) 영상 — 내용은 같아요"},
      {"id": "v_pose_dance", "type": "video", "icon": "🎥", "title": "바른 자세로 듣고 말해요(노래·율동)", "description": "노래에 맞춰 율동하며 자세 익히기.", "url": "https://www.youtube.com/watch?v=NhYpxnIs5zM", "video_id": "NhYpxnIs5zM", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["offline_activity", "cover"], "note": "2015 교육과정 판(1단원 바른 자세로 읽고 쓰기) 영상 — 내용은 같아요"},
      {"id": "kd_u2_l08_09", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 8~9차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l08_09.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb42", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 경험 발표하기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/4_듣기말하기/g1_kor_tb_42_경험발표하기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l09: [
      {"id": "v_u2_self_intro", "type": "video", "icon": "🎥", "title": "자기소개하기 — 영상", "description": "아직 알맞은 공개 영상을 못 찾았어요 — 유튜브에서 골라 주세요.", "url": "https://www.youtube.com/results?search_query=%EC%B4%88%EB%93%B1%201%ED%95%99%EB%85%84%20%EC%B9%9C%EA%B5%AC%EB%93%A4%20%EC%95%9E%EC%97%90%EC%84%9C%20%EC%9E%90%EA%B8%B0%EC%86%8C%EA%B0%9C%ED%95%98%EA%B8%B0", "source": "미확보", "status": "미확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "v_pose_song", "type": "video", "icon": "🎥", "title": "바른 자세로 듣고 말해요(노래)", "description": "듣고 말하는 자세를 노래로 익혀요.", "url": "https://www.youtube.com/watch?v=tUUZK5Wzhpw", "video_id": "tUUZK5Wzhpw", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"], "note": "2015 교육과정 판(1단원 바른 자세로 읽고 쓰기) 영상 — 내용은 같아요"},
      {"id": "kd_u2_l08_09", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 8~9차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l08_09.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb41", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 인사·소개하기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/4_듣기말하기/g1_kor_tb_41_인사소개하기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l10: [
      {"id": "v_listen_pose", "type": "video", "icon": "🎥", "title": "바르게 듣고 읽는 자세 익히기", "description": "교과서 그림으로 바르게 듣는 친구 찾기.", "url": "https://www.youtube.com/watch?v=OSFKLmh4-tU", "video_id": "OSFKLmh4-tU", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"], "note": "2015 교육과정 판(1단원 바른 자세로 읽고 쓰기) 영상 — 내용은 같아요"},
      {"id": "v_gyeong", "type": "video", "icon": "🎥", "title": "경청송", "description": "귀 기울여 듣는 약속을 노래로.", "url": "https://www.youtube.com/watch?v=6jgzWcuB_cI", "video_id": "6jgzWcuB_cI", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "kd_u2_l10_11", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 10~11차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l10_11.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb37", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 집중하여 듣기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/4_듣기말하기/g1_kor_tb_37_집중하여듣기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l11: [
      {"id": "v_story_words", "type": "video", "icon": "🎥", "title": "이야기를 듣고 낱말 읽기", "description": "이야기를 들은 뒤 나온 낱말을 따라 읽는 영상.", "url": "https://www.youtube.com/watch?v=k2-o764P-5c", "video_id": "k2-o764P-5c", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud", "concept"], "note": "2015 교육과정 판(1단원 바른 자세로 읽고 쓰기) 영상 — 내용은 같아요"},
      {"id": "v_gyeong", "type": "video", "icon": "🎥", "title": "경청송", "description": "귀 기울여 듣는 약속을 노래로.", "url": "https://www.youtube.com/watch?v=6jgzWcuB_cI", "video_id": "6jgzWcuB_cI", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "kd_u2_l10_11", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 10~11차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l10_11.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb43", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 중요 내용 확인하며 듣기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/4_듣기말하기/g1_kor_tb_43_중요내용확인듣기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u2_l12: [
      {"id": "v_complete", "type": "video", "icon": "🎥", "title": "받침 넣어 글자 완성하기", "description": "빈 받침 자리를 채워 글자를 완성하는 교과서 활동 영상.", "url": "https://www.youtube.com/watch?v=7yPX-enxyMQ", "video_id": "7yPX-enxyMQ", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_rightwrite", "type": "video", "icon": "🎥", "title": "받침이 있는 글자 바르게 쓰기", "description": "그림에 맞는 낱말 완성·잘못 쓴 받침 고쳐 쓰기(국어활동).", "url": "https://www.youtube.com/watch?v=k5SAZX4TXUE", "video_id": "k5SAZX4TXUE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "concept"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "kd_u2_l12", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 12차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l12.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u2_l13: [
      {"id": "v_cards", "type": "video", "icon": "🎥", "title": "글자 카드 놀이와 단원 정리", "description": "받침 글자 카드 놀이 후 정리 활동.", "url": "https://www.youtube.com/watch?v=cqsMAhKbcxA", "video_id": "cqsMAhKbcxA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review", "offline_activity"], "note": "2015 교육과정 판(6단원 받침이 있는 글자) 영상 — 내용은 같아요"},
      {"id": "v_ebs_all", "type": "video", "icon": "🎥", "title": "한글이 야호 — 기본받침·쌍자음·이중모음 총 복습", "description": "EBS 한글이 야호 복습편. 단원 마무리·기초 다지기에.", "url": "https://www.youtube.com/watch?v=aSbbf_GOIMw", "video_id": "aSbbf_GOIMw", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review", "summary"]},
      {"id": "kd_u2_l13", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 13차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/2단원_받침이있는글자를읽어요/g1_kor_u2_l13.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ]
  };
  Object.keys(R).forEach(function (k) { R[k] = R[k].concat(COMMON); });
  window.KT_RESOURCES["g1_korean"] = Object.assign(window.KT_RESOURCES["g1_korean"] || {}, R);
})();
