/* ============================================================================
   resources/g1_korean_u7.js — 케이티처 자료층 · 1학년 1학기 국어 7단원 「알맞은 낱말을 찾아요」
   2026-09-23 (자료층 3차, 베프). 표준 = resources/README.md · 꼴 = g1_korean_u1.js
   - 링크는 전부 웹 검색으로 실측한 것(온스쿨 1학년 국어 페이지·EBS 한글이 야호·울산 교육연구정보원 등). 지어낸 ID 0건.
   - ⚠️ 온스쿨 영상은 2015 교육과정 판이다 — 단원 번호·교과서 쪽수가 다르다(note에 적음).
   - 미확보 2자리: l03, l06 — 검색 카드로 남긴다.
   - 살아 있는지는 사람이 재생해 본다(삭제·비공개는 실기기에서만 잡힌다).
   ============================================================================ */
(function () {
  window.KT_RESOURCES = window.KT_RESOURCES || {};
  var COMMON = [{"id": "kd_u7_home", "type": "kedu", "icon": "🏠", "title": "자기주도 — 7단원 차시 목록", "description": "학생이 혼자 푸는 케이에듀 국어 차시 목록.", "url": "/grade1/semester1/korean/index.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}, {"id": "lk_u7_onschool", "type": "link", "icon": "🔗", "title": "온스쿨 1학년 국어 — 차시별 영상 모음(교사용)", "description": "실천교육교사모임 온스쿨. 이 단원 영상 대부분의 출처(2015 판 단원·쪽수).", "url": "https://sites.google.com/view/onschool/1%ED%95%99%EB%85%84/1%ED%95%99%EB%85%84-%EA%B5%AD%EC%96%B4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}, {"id": "lk_ebs_yaho2", "type": "link", "icon": "🔗", "title": "EBS 한글이 야호 2 — 받침 글자 회차 모음", "description": "니은·리을 받침 등 받침 글자 회차를 골라 볼 수 있는 EBS 공식 페이지.", "url": "https://home.ebs.co.kr/yaho2/main", "source": "EBS", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover", "concept"]}, {"id": "lk_ham_g1kor", "type": "link", "icon": "🔗", "title": "함쌤 초등교실 — 1학년 국어 재생목록", "description": "1학년 국어 플립러닝용 교사 제작 영상 목록.", "url": "https://www.youtube.com/playlist?list=PLPMdOUL8kbAl_S1_t1Zv-gg_9KgT_VEQR", "source": "교사 공개 채널", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}];
  var R = {
    u7_l01: [
      {"id": "v_pic_sent", "type": "video", "icon": "🎥", "title": "그림에 맞는 문장 만들기", "description": "그림을 보고 낱말을 골라 문장을 만드는 도입 영상.", "url": "https://www.youtube.com/watch?v=8L4Us-fK12Y", "video_id": "8L4Us-fK12Y", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_smart_word", "type": "video", "icon": "🎥", "title": "문장에 어울리는 낱말 넣기", "description": "빈자리에 알맞은 낱말을 넣는 설명 영상.", "url": "https://www.youtube.com/watch?v=pDzthgk7p-c", "video_id": "pDzthgk7p-c", "source": "스마트올(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l01_02", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 1~2차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l01_02.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb29", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 짧은 문장 읽기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/2_읽기/g1_kor_tb_29_짧은문장읽기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u7_l02: [
      {"id": "v_pic_sent2", "type": "video", "icon": "🎥", "title": "그림 보고 문장 만들기", "description": "친구들이 무엇을 하는지 문장으로 말해 보기.", "url": "https://www.youtube.com/watch?v=saN1qigljVA", "video_id": "saN1qigljVA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_pic_q", "type": "video", "icon": "🎥", "title": "그림 보고 물음에 답하기", "description": "여러 장면 그림을 보고 물음에 문장으로 답하기.", "url": "https://www.youtube.com/watch?v=sEPCPm8WSiE", "video_id": "sEPCPm8WSiE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["question", "concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l01_02", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 1~2차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l01_02.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l03: [
      {"id": "v_u7_ssang_batchim", "type": "video", "icon": "🎥", "title": "쌍받침 ㄲ·ㅆ 낱말 — 영상", "description": "아직 알맞은 공개 영상을 못 찾았어요 — 유튜브에서 골라 주세요.", "url": "https://www.youtube.com/results?search_query=%EC%B4%88%EB%93%B1%201%ED%95%99%EB%85%84%20%EC%8C%8D%EB%B0%9B%EC%B9%A8%20%E3%84%B2%20%E3%85%86%20%EB%82%B1%EB%A7%90%20%EC%9D%BD%EA%B8%B0", "source": "미확보", "status": "미확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "v_ebs_all", "type": "video", "icon": "🎥", "title": "한글이 야호 — 기본받침·쌍자음·이중모음 총 복습", "description": "EBS 한글이 야호 복습편. 단원 마무리·기초 다지기에.", "url": "https://www.youtube.com/watch?v=aSbbf_GOIMw", "video_id": "aSbbf_GOIMw", "source": "EBS", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"]},
      {"id": "kd_u7_l03", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 3차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l03.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb15", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 쌍자음", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/1_문법/g1_kor_tb_15_쌍자음.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u7_l04: [
      {"id": "v_box_word", "type": "video", "icon": "🎥", "title": "보기의 말을 넣어 문장 만들기", "description": "보기 낱말을 골라 그림에 어울리는 문장 만들기.", "url": "https://www.youtube.com/watch?v=svv36VNo7v4", "video_id": "svv36VNo7v4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_act_word", "type": "video", "icon": "🎥", "title": "그림 보고 알맞은 낱말 골라 문장 만들기(국어활동)", "description": "국어활동 풀이 영상.", "url": "https://www.youtube.com/watch?v=fylwkgMgIlg", "video_id": "fylwkgMgIlg", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l04_05", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 4~5차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l04_05.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l05: [
      {"id": "v_act_word", "type": "video", "icon": "🎥", "title": "그림 보고 알맞은 낱말 골라 문장 만들기(국어활동)", "description": "국어활동 풀이 영상.", "url": "https://www.youtube.com/watch?v=fylwkgMgIlg", "video_id": "fylwkgMgIlg", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_smart_word", "type": "video", "icon": "🎥", "title": "문장에 어울리는 낱말 넣기", "description": "빈자리에 알맞은 낱말을 넣는 설명 영상.", "url": "https://www.youtube.com/watch?v=pDzthgk7p-c", "video_id": "pDzthgk7p-c", "source": "스마트올(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l04_05", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 4~5차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l04_05.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb32", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 문장 완성하기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/3_쓰기/g1_kor_tb_32_문장완성하기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u7_l06: [
      {"id": "v_u7_isa", "type": "video", "icon": "🎥", "title": "'무엇은 무엇이다' 문장 — 영상", "description": "아직 알맞은 공개 영상을 못 찾았어요 — 유튜브에서 골라 주세요.", "url": "https://www.youtube.com/results?search_query=%EC%B4%88%EB%93%B1%201%ED%95%99%EB%85%84%20%EB%AC%B4%EC%97%87%EC%9D%80%20%EB%AC%B4%EC%97%87%EC%9D%B4%EB%8B%A4%20%EB%AC%B8%EC%9E%A5", "source": "미확보", "status": "미확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "v_sea", "type": "video", "icon": "🎥", "title": "바다 풍경 보고 문장 만들기", "description": "풍경 속 사물을 문장으로 나타내기(국어활동).", "url": "https://www.youtube.com/watch?v=efyFDRFpsvE", "video_id": "efyFDRFpsvE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "leveled_problem"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l06_08", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 6~8차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l06_08.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l07: [
      {"id": "v_who_what", "type": "video", "icon": "🎥", "title": "동물들이 무엇을 하는지 문장으로 잇기", "description": "토끼·사자·악어·기린이 무엇을 하는지 문장으로.", "url": "https://www.youtube.com/watch?v=0AJT5yDGVW8", "video_id": "0AJT5yDGVW8", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_party", "type": "video", "icon": "🎥", "title": "동물 잔치 그림 보고 문장 쓰기", "description": "누가 무엇을 하는지 문장으로 써 보는 영상.", "url": "https://www.youtube.com/watch?v=6ls_LkcXjik", "video_id": "6ls_LkcXjik", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l06_08", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 6~8차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l06_08.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb31", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 문장 따라 쓰기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/3_쓰기/g1_kor_tb_31_문장따라쓰기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u7_l08: [
      {"id": "v_example", "type": "video", "icon": "🎥", "title": "<보기>처럼 문장 만들기", "description": "보기 문장의 모양을 따라 새 문장 만들기.", "url": "https://www.youtube.com/watch?v=QKJPdXeGPD4", "video_id": "QKJPdXeGPD4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "leveled_problem"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_right_sent", "type": "video", "icon": "🎥", "title": "바르게 표현한 문장 고르기", "description": "뜻이 잘 통하는 문장에 ○표 하는 활동.", "url": "https://www.youtube.com/watch?v=a1gMVaGAm4k", "video_id": "a1gMVaGAm4k", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["card_quiz", "review"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l06_08", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 6~8차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l06_08.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l09: [
      {"id": "v_pic_story", "type": "video", "icon": "🎥", "title": "그림 보고 이야기 만들기", "description": "장면마다 누가 무엇을 하는지 문장으로 잇기.", "url": "https://www.youtube.com/watch?v=NTIJNQb1zjw", "video_id": "NTIJNQb1zjw", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_pic_q", "type": "video", "icon": "🎥", "title": "그림 보고 물음에 답하기", "description": "여러 장면 그림을 보고 물음에 문장으로 답하기.", "url": "https://www.youtube.com/watch?v=sEPCPm8WSiE", "video_id": "sEPCPm8WSiE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["question", "concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l09_10", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 9~10차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l09_10.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l10: [
      {"id": "v_draw_sent", "type": "video", "icon": "🎥", "title": "그림 그리고 문장 만들기", "description": "내가 그린 그림을 문장으로 나타내기.", "url": "https://www.youtube.com/watch?v=4klO2tCit6c", "video_id": "4klO2tCit6c", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_pic_sent3", "type": "video", "icon": "🎥", "title": "그림에 어울리는 문장 만들기", "description": "교과서 그림으로 문장 만드는 활동 영상.", "url": "https://www.youtube.com/watch?v=62SpjzcA0Vg", "video_id": "62SpjzcA0Vg", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l09_10", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 9~10차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l09_10.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l11: [
      {"id": "v_quiz_sent", "type": "video", "icon": "🎥", "title": "문장 만들기 퀴즈 놀이", "description": "문장 만들기 퀴즈(상업 채널).", "url": "https://www.youtube.com/watch?v=F-u31cyLEeo", "video_id": "F-u31cyLEeo", "source": "캐리와친구들(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["card_quiz"]},
      {"id": "v_pic_sent4", "type": "video", "icon": "🎥", "title": "그림 속 내용으로 문장 만들기", "description": "그림 속 인물·행동을 문장으로 말하기.", "url": "https://www.youtube.com/watch?v=i6f1fGmPWLU", "video_id": "i6f1fGmPWLU", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "card_quiz"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l11_12", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 11~12차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l11_12.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l12: [
      {"id": "v_photo_sent", "type": "video", "icon": "🎥", "title": "사진 보고 문장 만들기", "description": "사진 속 장면을 문장으로 만드는 방법.", "url": "https://www.youtube.com/watch?v=ayMQPlTFHzI", "video_id": "ayMQPlTFHzI", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["offline_activity", "concept"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_family_photo", "type": "video", "icon": "🎥", "title": "가족사진 보고 문장 만들기", "description": "가족사진으로 문장 만들기 시범.", "url": "https://www.youtube.com/watch?v=TE3MVGN-WdI", "video_id": "TE3MVGN-WdI", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l11_12", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 11~12차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l11_12.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l13: [
      {"id": "v_good", "type": "video", "icon": "🎥", "title": "'좋겠다'로 문장 만들기", "description": "시를 읽고 '누구는 좋겠다' 문장 만들기.", "url": "https://www.youtube.com/watch?v=QhGHfP9Fd6s", "video_id": "QhGHfP9Fd6s", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review", "offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_pic_sent4", "type": "video", "icon": "🎥", "title": "그림 속 내용으로 문장 만들기", "description": "그림 속 인물·행동을 문장으로 말하기.", "url": "https://www.youtube.com/watch?v=i6f1fGmPWLU", "video_id": "i6f1fGmPWLU", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l13_14", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 13~14차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l13_14.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u7_l14: [
      {"id": "v_notebook", "type": "video", "icon": "🎥", "title": "낱말 불리기 수첩 만들기", "description": "배운 낱말을 모으는 수첩 만드는 법.", "url": "https://www.youtube.com/watch?v=TBg8aU0opRE", "video_id": "TBg8aU0opRE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "offline_activity"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요", "audience": "teacher"},
      {"id": "v_draw_sent", "type": "video", "icon": "🎥", "title": "그림 그리고 문장 만들기", "description": "내가 그린 그림을 문장으로 나타내기.", "url": "https://www.youtube.com/watch?v=4klO2tCit6c", "video_id": "4klO2tCit6c", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u7_l13_14", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 13~14차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/7단원_알맞은낱말을찾아요/g1_kor_u7_l13_14.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ]
  };
  Object.keys(R).forEach(function (k) { R[k] = R[k].concat(COMMON); });
  window.KT_RESOURCES["g1_korean"] = Object.assign(window.KT_RESOURCES["g1_korean"] || {}, R);
})();
