/* ============================================================================
   resources/g1_korean_u6.js — 케이티처 자료층 · 1학년 1학기 국어 6단원 「또박또박 읽어요」
   2026-09-23 (자료층 3차, 베프). 표준 = resources/README.md · 꼴 = g1_korean_u1.js
   - 링크는 전부 웹 검색으로 실측한 것(온스쿨 1학년 국어 페이지·EBS 한글이 야호·울산 교육연구정보원 등). 지어낸 ID 0건.
   - ⚠️ 온스쿨 영상은 2015 교육과정 판이다 — 단원 번호·교과서 쪽수가 다르다(note에 적음).
   - 미확보 1자리: l11 — 검색 카드로 남긴다.
   - 살아 있는지는 사람이 재생해 본다(삭제·비공개는 실기기에서만 잡힌다).
   ============================================================================ */
(function () {
  window.KT_RESOURCES = window.KT_RESOURCES || {};
  var COMMON = [{"id": "kd_u6_home", "type": "kedu", "icon": "🏠", "title": "자기주도 — 6단원 차시 목록", "description": "학생이 혼자 푸는 케이에듀 국어 차시 목록.", "url": "/grade1/semester1/korean/index.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}, {"id": "lk_u6_onschool", "type": "link", "icon": "🔗", "title": "온스쿨 1학년 국어 — 차시별 영상 모음(교사용)", "description": "실천교육교사모임 온스쿨. 이 단원 영상 대부분의 출처(2015 판 단원·쪽수).", "url": "https://sites.google.com/view/onschool/1%ED%95%99%EB%85%84/1%ED%95%99%EB%85%84-%EA%B5%AD%EC%96%B4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}, {"id": "lk_ulsan_basic", "type": "link", "icon": "🔗", "title": "울산교육연구정보원 — 교수학습콘텐츠 자료실", "description": "「단단한 한글」 초기 문해력 영상·교재가 올라오는 교육청 자료실.", "url": "https://use.go.kr/edu/user/bbs/BD_selectBbs.do?q_bbsSn=1696&q_bbsDocNo=1682", "source": "울산광역시교육연구정보원", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}, {"id": "lk_ham_g1kor", "type": "link", "icon": "🔗", "title": "함쌤 초등교실 — 1학년 국어 재생목록", "description": "1학년 국어 플립러닝용 교사 제작 영상 목록.", "url": "https://www.youtube.com/playlist?list=PLPMdOUL8kbAl_S1_t1Zv-gg_9KgT_VEQR", "source": "교사 공개 채널", "status": "확보", "verified": "2026-09-23", "audience": "teacher", "fit_slides": ["cover"]}];
  var R = {
    u6_l01: [
      {"id": "v_ah_tooth", "type": "video", "icon": "🎥", "title": "'아! 이가 아파요'와 '아이가 아파요'", "description": "띄어 읽기에 따라 뜻이 달라지는 도입 영상.", "url": "https://www.youtube.com/watch?v=2JDQcTnYcPc", "video_id": "2JDQcTnYcPc", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_elihi", "type": "video", "icon": "🎥", "title": "띄어 읽으면 좋은 점 알기", "description": "띄어 읽기 개념 설명(상업 채널).", "url": "https://www.youtube.com/watch?v=3lGv7PQ1iqs", "video_id": "3lGv7PQ1iqs", "source": "엘리하이(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l01", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 1차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l01.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb30", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 띄어 읽기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/2_읽기/g1_kor_tb_30_띄어읽기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l02: [
      {"id": "v_ulsan_read", "type": "video", "icon": "🎥", "title": "여러 가지 방법으로 소리 내어 읽기(2)", "description": "울산 초기 문해력 콘텐츠. 1·2학년 소리 내어 읽기 연습.", "url": "https://www.youtube.com/watch?v=5fJyVu6T7dQ", "video_id": "5fJyVu6T7dQ", "source": "울산광역시교육연구정보원", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud", "concept"]},
      {"id": "v_snail", "type": "video", "icon": "🎥", "title": "「달팽이 기르기」 소리 내어 읽기", "description": "여러 문장이 이어진 글을 소리 내어 읽는 영상.", "url": "https://www.youtube.com/watch?v=A-DSXIjGB8k", "video_id": "A-DSXIjGB8k", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l02_03", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 2~3차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l02_03.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb29", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 짧은 문장 읽기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/2_읽기/g1_kor_tb_29_짧은문장읽기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l03: [
      {"id": "v_snail", "type": "video", "icon": "🎥", "title": "「달팽이 기르기」 소리 내어 읽기", "description": "여러 문장이 이어진 글을 소리 내어 읽는 영상.", "url": "https://www.youtube.com/watch?v=A-DSXIjGB8k", "video_id": "A-DSXIjGB8k", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_ball", "type": "video", "icon": "🎥", "title": "「공 나르기」와 띄어 읽으면 좋은 점", "description": "글을 채워 읽으며 띄어 읽기의 좋은 점 정리.", "url": "https://www.youtube.com/watch?v=adYAl2E8ahA", "video_id": "adYAl2E8ahA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "question"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l02_03", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 2~3차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l02_03.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l04: [
      {"id": "v_no_space", "type": "video", "icon": "🎥", "title": "띄어 읽지 않으면 어떻게 될까요?", "description": "붙여 읽어 뜻이 헷갈리는 장면 보기.", "url": "https://www.youtube.com/watch?v=Wu_Gv3lfZBM", "video_id": "Wu_Gv3lfZBM", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_ah_tooth", "type": "video", "icon": "🎥", "title": "'아! 이가 아파요'와 '아이가 아파요'", "description": "띄어 읽기에 따라 뜻이 달라지는 도입 영상.", "url": "https://www.youtube.com/watch?v=2JDQcTnYcPc", "video_id": "2JDQcTnYcPc", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l04_05", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 4~5차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l04_05.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l05: [
      {"id": "v_ball", "type": "video", "icon": "🎥", "title": "「공 나르기」와 띄어 읽으면 좋은 점", "description": "글을 채워 읽으며 띄어 읽기의 좋은 점 정리.", "url": "https://www.youtube.com/watch?v=adYAl2E8ahA", "video_id": "adYAl2E8ahA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "question"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_snail_q", "type": "video", "icon": "🎥", "title": "「달팽이 기르기」 물음에 답하고 정리하기", "description": "읽은 글의 뜻을 묻고 답하는 활동.", "url": "https://www.youtube.com/watch?v=JJ_8k03bX6I", "video_id": "JJ_8k03bX6I", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["question", "review"], "note": "2015 교육과정 판(7단원 생각을 나타내요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l04_05", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 4~5차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l04_05.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l06: [
      {"id": "v_punct", "type": "video", "icon": "🎥", "title": "문장 부호에 대해 알아보기", "description": "마침표·쉼표·물음표·느낌표를 노래와 함께 알아봐요.", "url": "https://www.youtube.com/watch?v=-qeeuCt60tY", "video_id": "-qeeuCt60tY", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_punct4", "type": "video", "icon": "🎥", "title": "문장 부호 사총사 노래", "description": "네 가지 문장 부호를 노래로.", "url": "https://www.youtube.com/watch?v=FbHCNwcwYUo", "video_id": "FbHCNwcwYUo", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l06_07", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 6~7차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l06_07.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb27", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 문장과 마침표", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/1_문법/g1_kor_tb_27_문장과마침표.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l07: [
      {"id": "v_tiger_p", "type": "video", "icon": "🎥", "title": "「호랑이 형님」 읽으며 문장 부호 쓰임 알기", "description": "이야기 속 문장 부호가 하는 일 찾기.", "url": "https://www.youtube.com/watch?v=xesUHiydzkg", "video_id": "xesUHiydzkg", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "read_aloud"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_punct_song", "type": "video", "icon": "🎥", "title": "문장 부호 노래", "description": "문장 부호 이름과 모양 노래.", "url": "https://www.youtube.com/watch?v=bgQ7_otDSGA", "video_id": "bgQ7_otDSGA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "cover"]},
      {"id": "kd_u6_l06_07", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 6~7차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l06_07.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb28", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 물음표·느낌표", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/1_문법/g1_kor_tb_28_물음표느낌표.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l08: [
      {"id": "v_pause", "type": "video", "icon": "🎥", "title": "문장 부호에 맞게 띄어 읽기·부호 쓰기", "description": "국어활동 풀이 — 부호 뒤에서 쉬어 읽기.", "url": "https://www.youtube.com/watch?v=k1gBvaBoNGE", "video_id": "k1gBvaBoNGE", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["concept", "read_aloud"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_bear_fox", "type": "video", "icon": "🎥", "title": "문장 부호에 주의하며 「곰과 여우」 읽기", "description": "부호에 맞게 쉬며 읽는 연습 영상.", "url": "https://www.youtube.com/watch?v=OASW_zIKZUA", "video_id": "OASW_zIKZUA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l08_09", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 8~9차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l08_09.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb30", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 띄어 읽기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/2_읽기/g1_kor_tb_30_띄어읽기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l09: [
      {"id": "v_bear_fox", "type": "video", "icon": "🎥", "title": "문장 부호에 주의하며 「곰과 여우」 읽기", "description": "부호에 맞게 쉬며 읽는 연습 영상.", "url": "https://www.youtube.com/watch?v=OASW_zIKZUA", "video_id": "OASW_zIKZUA", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud", "motivate"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_ulsan_book", "type": "video", "icon": "🎥", "title": "'우리아이' 그림책 활용 안내", "description": "울산 초기 문해력 콘텐츠 — 그림책 함께 읽기 지도 안내.", "url": "https://www.youtube.com/watch?v=Fl9swmCLBrw", "video_id": "Fl9swmCLBrw", "source": "울산광역시교육연구정보원", "status": "확보", "verified": "2026-09-23", "fit_slides": ["cover"], "audience": "teacher"},
      {"id": "v_punct_rev", "type": "video", "icon": "🎥", "title": "문장 부호의 쓰임 복습", "description": "부호별 쓰임을 다시 짚는 복습 영상.", "url": "https://www.youtube.com/watch?v=zvhzieJGZUs", "video_id": "zvhzieJGZUs", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review", "concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l08_09", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 8~9차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l08_09.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]},
      {"id": "kd_tb49", "type": "kedu", "icon": "🏠", "title": "자기주도 교과 밖 — 그림책 읽기", "description": "교과서 차시와 따로 도는 케이에듀 연습 화면. 더 연습할 아이에게.", "url": "/grade1/semester1/korean/5_문학/g1_kor_tb_49_그림책읽기.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["leveled_problem", "summary"]}
    ],
    u6_l10: [
      {"id": "v_tiger_story", "type": "video", "icon": "🎥", "title": "「호랑이 형님」 이야기 듣기", "description": "옛이야기 영상(상업 채널). 인물 목소리 떠올리기에.", "url": "https://www.youtube.com/watch?v=lK32S5e0ytw", "video_id": "lK32S5e0ytw", "source": "지니키즈(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "read_aloud"]},
      {"id": "v_tiger_read", "type": "video", "icon": "🎥", "title": "「호랑이 형님」 소리 내어 읽기", "description": "문장 부호에 주의하며 읽는 교과서 활동 영상.", "url": "https://www.youtube.com/watch?v=iFlDFCv5Qw4", "video_id": "iFlDFCv5Qw4", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["read_aloud"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l10_11", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 10~11차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l10_11.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l11: [
      {"id": "v_u6_voice_play", "type": "video", "icon": "🎥", "title": "목소리 연극 발표 — 영상", "description": "아직 알맞은 공개 영상을 못 찾았어요 — 유튜브에서 골라 주세요.", "url": "https://www.youtube.com/results?search_query=%EC%B4%88%EB%93%B1%201%ED%95%99%EB%85%84%20%EB%AA%A9%EC%86%8C%EB%A6%AC%20%EC%97%B0%EA%B7%B9", "source": "미확보", "status": "미확보", "verified": "2026-09-23", "fit_slides": ["cover", "motivate"]},
      {"id": "v_tiger_story", "type": "video", "icon": "🎥", "title": "「호랑이 형님」 이야기 듣기", "description": "옛이야기 영상(상업 채널). 인물 목소리 떠올리기에.", "url": "https://www.youtube.com/watch?v=lK32S5e0ytw", "video_id": "lK32S5e0ytw", "source": "지니키즈(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["motivate", "read_aloud"]},
      {"id": "kd_u6_l10_11", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 10~11차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l10_11.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l12: [
      {"id": "v_punct_put", "type": "video", "icon": "🎥", "title": "알맞은 문장 부호 넣기", "description": "빈칸에 맞는 부호를 고르는 활동 영상.", "url": "https://www.youtube.com/watch?v=uWrWbQ9LfWg", "video_id": "uWrWbQ9LfWg", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["card_quiz", "review"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_punct4", "type": "video", "icon": "🎥", "title": "문장 부호 사총사 노래", "description": "네 가지 문장 부호를 노래로.", "url": "https://www.youtube.com/watch?v=FbHCNwcwYUo", "video_id": "FbHCNwcwYUo", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l12_13", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 12~13차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l12_13.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ],
    u6_l13: [
      {"id": "v_punct_rev", "type": "video", "icon": "🎥", "title": "문장 부호의 쓰임 복습", "description": "부호별 쓰임을 다시 짚는 복습 영상.", "url": "https://www.youtube.com/watch?v=zvhzieJGZUs", "video_id": "zvhzieJGZUs", "source": "온스쿨(교사 공개)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review", "concept"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "v_elihi", "type": "video", "icon": "🎥", "title": "띄어 읽으면 좋은 점 알기", "description": "띄어 읽기 개념 설명(상업 채널).", "url": "https://www.youtube.com/watch?v=3lGv7PQ1iqs", "video_id": "3lGv7PQ1iqs", "source": "엘리하이(온스쿨 수록)", "status": "확보", "verified": "2026-09-23", "fit_slides": ["review"], "note": "2015 교육과정 판(8단원 소리 내어 또박또박 읽어요) 영상 — 교과서 쪽수는 달라요"},
      {"id": "kd_u6_l12_13", "type": "kedu", "icon": "🏠", "title": "자기주도 차시 — 12~13차시", "description": "같은 차시의 학생용 케이에듀 화면.", "url": "/grade1/semester1/korean/6단원_또박또박읽어요/g1_kor_u6_l12_13.html", "source": "케이에듀", "status": "확보", "verified": "2026-09-23", "fit_slides": ["summary", "next_lesson"]}
    ]
  };
  Object.keys(R).forEach(function (k) { R[k] = R[k].concat(COMMON); });
  window.KT_RESOURCES["g1_korean"] = Object.assign(window.KT_RESOURCES["g1_korean"] || {}, R);
})();
