/* 케이파크 · 마블런 — tracks.js
 * 프리셋 트랙 (단일 소스). 빌더 데이터 모델(startH + seq)로 정의 —
 * "예시 불러오기 → 이어서 편집"이 가능한 구조.
 * 모든 트랙은 compile + buildTrack + 완주 테스트를 통과해야 함.
 */
(function (root, factory) {
  const mod = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = mod;
  root.MarbleSim = Object.assign(root.MarbleSim || {}, mod);
})(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';

  const TRACKS = [
    {
      id: 'showcase',
      name: '✨ 별빛 대서커스',
      desc: '자이로·하늘 비행·루프 2번·대포·트램펄린·리프터 총출동 — 구슬 3개의 대공연!',
      startH: 6,
      marbles: 3,
      seq: ['slope', 'gyro', 'slope', 'booster', 'hill', 'straight', 'straight', 'curve_l', 'loop',
        'slope', 'straight', 'cannon', 'slope', 'trampoline', 'curve_r', 'zigzag',
        'lifter', 'curve_l', 'slope', 'booster', 'booster', 'loop', 'slope',
        { type: 'switch',
          left:  ['curve_l', 'goal'],
          right: ['curve_r', 'goal'] }],
    },
    {
      id: 'golden',
      name: '골든 샘플',
      desc: '기본 코스 — 탑에서 내려와 커브 돌고 벨까지',
      startH: 2,
      seq: ['slope', 'slope', 'straight', 'curve_l', 'goal'],
    },
    {
      id: 'slalom',
      name: 'S자 슬라럼',
      desc: '높이 3에서 좌우로 굽이치며 내려오는 코스',
      startH: 3,
      seq: ['slope', 'slope', 'curve_l', 'slope', 'curve_r', 'straight', 'goal'],
    },
    {
      id: 'spiral',
      name: '나선 폭포',
      desc: '높이 4 — 빙글빙글 돌며 떨어지는 최장 낙차 코스',
      startH: 4,
      seq: ['slope', 'curve_l', 'slope', 'curve_l', 'slope', 'curve_l', 'slope', 'straight', 'goal'],
    },
    {
      id: 'grandtour',
      name: '그랜드 투어',
      desc: '낮은 낙차로 얼마나 멀리 가나 — 마찰과의 싸움',
      startH: 2,
      seq: ['slope', 'slope', 'straight', 'straight', 'curve_l', 'curve_l', 'straight', 'straight', 'curve_r', 'goal'],
    },
    {
      id: 'fullcourse',
      name: '풀코스 스페셜',
      desc: '자이로·언덕·루프·점프·부스터 총출동 — 전 부품 시연',
      startH: 5,
      seq: ['slope', 'gyro', 'curve_l', 'slope', 'hill', 'booster', 'curve_r', 'loop', 'slope', 'jump', 'zigzag', 'goal'],
    },
    {
      id: 'loopchallenge',
      name: '루프 챌린지',
      desc: '느리면 꼭대기에서 떨어진다! 부스터 2개의 힘',
      startH: 2,
      seq: ['slope', 'booster', 'booster', 'loop', 'slope', 'straight', 'goal'],
    },
    {
      id: 'cannonrange',
      name: '대포 발사대',
      desc: '3칸을 날아 착지대에 꽂힌다 — 대포는 스스로 밀어준다',
      startH: 5,
      seq: ['straight', 'cannon', 'slope', 'booster', 'loop', 'slope', 'goal'],
    },
    {
      id: 'trampolinepark',
      name: '트램펄린 파크',
      desc: '통통 두 번 튕겨서 건너가는 코스',
      startH: 3,
      seq: ['slope', 'trampoline', 'curve_l', 'trampoline', 'straight', 'goal'],
    },
    {
      id: 'skyroute',
      name: '공중 대탐험',
      desc: '대포로 날고 트램펄린으로 튕기고 — 땅에 거의 안 닿는 코스',
      startH: 5,
      seq: ['straight', 'cannon', 'slope', 'trampoline', 'curve_r', 'goal'],
    },
    {
      id: 'forkplaza',
      name: '갈림길 광장',
      desc: '구슬 3개를 굴려봐 — 스위치가 딸깍딸깍 번갈아 보낸다!',
      startH: 3,
      marbles: 3,
      seq: ['slope', 'straight',
        { type: 'switch',
          left:  ['curve_l', 'slope', 'straight', 'goal'],
          right: ['curve_r', 'slope', 'straight', 'goal'] }],
    },
    {
      id: 'triplebell',
      name: '세 갈래 종탑',
      desc: '갈래 속의 갈래 — 벨 3개가 누구를 먼저 맞이할까?',
      startH: 4,
      marbles: 3,
      seq: ['slope',
        { type: 'switch',
          left: ['curve_l', 'slope',
            { type: 'switch',
              left:  ['curve_l', 'goal'],
              right: ['curve_r', 'straight', 'goal'] }],
          right: ['curve_r', 'slope', 'zigzag', 'goal'] }],
    },
    {
      id: 'flyinghill',
      name: '날아라 언덕',
      desc: '부스터 기세로 마루에서 붕 — 날아서 레일에 착지한다!',
      startH: 4,
      seq: ['slope', 'booster', 'booster', 'hill', 'straight', 'straight', 'goal'],
    },
    {
      id: 'reunion',
      name: '다시 만나는 길',
      desc: '🤝 스위치가 번갈아 보내도 두 길은 다시 하나로 — 벨은 하나!',
      startH: 3,
      marbles: 3,
      seq: ['slope',
        { type: 'switch',
          left:  ['curve_r', 'slope', 'curve_r'],
          right: ['curve_l', 'slope', 'curve_l'],
          merged: true,
          tail: ['slope', 'goal'] }],
    },
    {
      id: 'signaltower',
      name: '신호기 관제탑',
      desc: '🚦 신호기는 네가 정한 길로만 보낸다 — 실행 중에 탭해서 길을 바꿔봐!',
      startH: 3,
      marbles: 3,
      seq: ['slope', 'straight',
        { type: 'splitter',
          left:  ['curve_l', 'slope', 'straight', 'goal'],
          right: ['curve_r', 'slope', 'straight', 'goal'] }],
    },
    {
      id: 'sortery',
      name: '마법 분류소',
      desc: '🎨 색 게이트에 막히면 팅! 되돌아가 스위치를 딸깍 — 구슬이 스스로 제 색 문을 찾아간다!',
      startH: 3,
      marbles: 3,
      seq: ['slope', 'slope',
        { type: 'switch',
          left:  [{ type: 'colorgate', color: 1 }, 'curve_l', 'goal'],
          right: [{ type: 'switch',
            left:  [{ type: 'colorgate', color: 0 }, 'goal'],
            right: [{ type: 'colorgate', color: 2 }, 'curve_r', 'goal'] }] }],
    },
    {
      id: 'photofinish',
      name: '번개 결승선',
      desc: '🏁 지그재그 길 vs 부스터 길 — 결승 아치가 1000분의 1초까지 판정한다!',
      startH: 3,
      marbles: 2,
      seq: ['slope',
        { type: 'switch',
          left:  ['curve_r', 'zigzag', 'curve_r'],
          right: ['curve_l', 'booster', 'curve_l'],
          merged: true,
          tail: ['racegate', 'slope', 'goal'] }],
    },
    {
      id: 'orgolnight',
      name: '오르골의 밤',
      desc: '🎼 도미노가 와르르, 구슬 다섯이 도착할 때마다 멜로디 한 음씩 — 트랙이 악기가 된다',
      startH: 4,
      marbles: 5,
      seq: ['slope', 'domino', 'slope', 'curve_l', 'slope', 'straight', 'curve_l', 'slope', 'domino', 'orgol'],
    },
    {
      id: 'skyelevator',
      name: '두둥실 리프트',
      desc: '바닥까지 내려온 구슬을 리프터가 2칸 들어올린다 — 두 번째 활강!',
      startH: 2,
      seq: ['slope', 'slope', 'straight', 'lifter', 'curve_l', 'slope', 'curve_r', 'slope', 'straight', 'goal'],
    },
  ];

  return { TRACKS };
});
