// 통일신라·발해 넓은 터 GLB 구조 검증 — NPC 18·구역 13·spawn·미션·숨김 재질(석굴 부처·붉은 바지·깃발 셋)이 json 과 맞는지 (WebGL 없이 GLB JSON 청크만)
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base = new URL('../eras/silla-life/', import.meta.url);
const buffer = fs.readFileSync(new URL('silla.glb', base));
const data = JSON.parse(buffer.subarray(20, 20 + buffer.readUInt32LE(12)).toString());
const read = (f) => JSON.parse(fs.readFileSync(new URL(f, base)));
const world = read('world.json'), items = read('items.json'), npcDefs = read('npcs.json'), missions = read('missions.json'), scene = read('scene.json'), life = read('life.json');
const sceneTypes = new Set((scene.add || []).map((a) => a.name.split('_')[0]));
const names = data.nodes.map((n) => n.name || '');
const ix = names.filter((n) => n.startsWith('ix_'));
const types = new Set(ix.map((n) => n.split('_')[1]));
for (const t of types) assert.ok(items.targets[t], `대상 ${t} 가 items.json 에 없음`);
for (const t of Object.keys(items.targets)) assert.ok(types.has(t) || sceneTypes.has(t), `items.json 대상 ${t} 가 GLB·scene 에 없음`);
const areas = names.filter((n) => n.startsWith('area_')).map((n) => n.slice(5));
for (const a of Object.keys(world.areas)) assert.ok(areas.includes(a), `구역 ${a} 없음`);
assert.equal(Object.keys(world.areas).length, 13, '구역 13');
assert.ok(areas.includes(world.face), `시작 시선 구역 ${world.face}`);
assert.ok(names.includes('spawn'), 'spawn');
const npcs = ix.filter((n) => n.startsWith('ix_npc_')).map((n) => n.slice(7));
for (const id of Object.keys(npcDefs)) assert.ok(npcs.includes(id), `NPC ${id} 가 GLB 에 없음`);
for (const id of npcs) assert.ok(npcDefs[id], `GLB NPC ${id} 가 npcs.json 에 없음`);
assert.equal(npcs.length, 18, 'NPC 18');
const mats = new Set((data.materials || []).map((m) => m.name));
for (const t of ['grotto_buddha', 'red_cloth', 'flag_gyeon', 'flag_gung', 'flag_wang']) assert.ok(mats.has(t), `숨김 재질 ${t}`);
assert.ok(ix.filter((n) => n.startsWith('ix_mulberry_')).length === 6 && ix.filter((n) => n.startsWith('ix_stair_')).length === 1 && ix.filter((n) => n.startsWith('ix_pagoda_')).length === 2 && ix.filter((n) => n.startsWith('ix_ship_')).length === 2 && ix.filter((n) => n.startsWith('ix_stoneman_')).length === 2, '뽕나무 6·벼슬 계단 1·석탑 2·배 2·무인석 2');
const list = missions.missions;
assert.equal(list.length, 7, '꼭 나오는 상황 7 = 미션 7');
const must = life.situations.filter((x) => x.must); assert.equal(must.length, 7, '꼭 나오는 상황 7'); assert.ok(life.situations.length - must.length >= life.mixedCount, '섞여 나오는 상황 ≥ mixedCount');
for (const m of list) assert.ok(must.some((x) => 'sit:' + x.id + ':done' === m.done), `미션 ${m.id} 가 상황과 안 맞음`);
for (const sit of life.situations) { if (sit.place) assert.ok(world.areas[sit.place], `상황 ${sit.id} 장소 ${sit.place}`); for (const c of sit.choices) assert.ok(c.done || c.count, `상황 ${sit.id} 선택 ${c.id} 에 done/count 없음`); }
assert.ok(life.grain?.open && life.rank?.open && life.carry?.from === 'samguk-life', '곡식 칸 + 벼슬 칸(천장) + 삼국에서 넘겨받음');
const st = life.status.rules; assert.ok(new Set(st.map((r) => r.id)).size === 11 && st.find((r) => r.id === 'jingol').cap === 6 && st.find((r) => r.id === 'six').cap === 3 && st.find((r) => r.id === 'low').cap === 1 && st.find((r) => r.id === 'farmer').cap === 0 && st.find((r) => r.id === 'retainer').cap === undefined, '신분 11 + 천장 숫자(진골 6·6두품 3·두품 1·평민 0·호족의 사람 없음)');
assert.ok(new Set(life.nation?.rules.map((r) => r.id)).size === 2, '나라 둘(통일신라·발해)');
assert.ok(life.hurts?.wound && world.danger?.safe?.length === 3, '흔적 「다친 몸」 + 마을·호족 집·관아 밤 안전 자리');
assert.ok(world.hideHunger && world.hunger.perSecond === 0, '배고픔 없음');
const prev = JSON.parse(fs.readFileSync(new URL('../eras/samguk-life/world.json', import.meta.url))); assert.ok(prev.gate?.next === 'silla-life' && prev.gate.ready, '삼국 끝 카드 → 통일신라·발해 문(열림)');
const h = read('height.json'); assert.ok(h && typeof h === 'object', 'height.json');
console.log(`silla.glb: ix ${ix.length} (${[...types].join(',')}) · areas ${areas.length} · npc ${npcs.length} · ${(buffer.length / 1e6).toFixed(2)}MB`);
