// 개항~일제 인생 층 구조 검증 — 새 터 gaehang.glb(bpy gaehang_land.py): ix 22 + NPC 18 · 구역 20 · 미션 8 · 숨김 재질(일장기 sunred, 1910 토지 조사 때 보임) · done 깃발 전수 · 직업 카드 14(천장: 협력 6 / 쫓기는 몸 0 / 나머지 4) · 끝 갈림 45 · 조선 후기에서 넘겨받음 · 문 → 대한민국(준비 중)
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base = new URL('../eras/gaehang-life/', import.meta.url);
const read = (f) => JSON.parse(fs.readFileSync(new URL(f, base)));
const world = read('world.json'), items = read('items.json'), npcDefs = read('npcs.json'), missions = read('missions.json'), scene = read('scene.json'), life = read('life.json');
assert.equal(world.glb, 'gaehang.glb', '새 터');
const buffer = fs.readFileSync(new URL(world.glb, base));
const data = JSON.parse(buffer.subarray(20, 20 + buffer.readUInt32LE(12)).toString());
assert.deepEqual(scene.add || [], [], 'scene.add 없음 — 자리는 전부 GLB');
const names = data.nodes.map((n) => n.name || '');
const ix = names.filter((n) => n.startsWith('ix_'));
const types = new Set(ix.map((n) => n.split('_')[1]));
for (const t of types) assert.ok(items.targets[t], `대상 ${t} 가 items.json 에 없음`);
for (const t of Object.keys(items.targets)) assert.ok(types.has(t), `items.json 대상 ${t} 가 GLB 에 없음`);
const areas = names.filter((n) => n.startsWith('area_')).map((n) => n.slice(5));
for (const a of Object.keys(world.areas)) assert.ok(areas.includes(a), `구역 ${a} 없음`);
assert.equal(Object.keys(world.areas).length, 20, '구역 20'); assert.ok(areas.includes(world.face) && names.includes('spawn'), `시작 시선 구역 ${world.face} + spawn`);
const npcs = ix.filter((n) => n.startsWith('ix_npc_')).map((n) => n.slice(7));
for (const id of Object.keys(npcDefs)) assert.ok(npcs.includes(id), `NPC ${id} 가 GLB 에 없음`);
for (const id of npcs) assert.ok(npcDefs[id], `GLB NPC ${id} 가 npcs.json 에 없음`);
assert.equal(npcs.length, 18, 'NPC 18'); assert.equal(ix.length - npcs.length, 22, '상호작용 자리 22');
for (const k of ['jeonbongjun', 'parkseongchun', 'ahnjunggeun', 'yugwansun', 'jusigyeong', 'kimgu', 'yundongju']) assert.ok(npcDefs[k], `인물 카드 ${k}`);
const mats = new Set((data.materials || []).map((m) => m.name));
for (const [t, h] of Object.entries(items.targets)) for (const m of h.hidden || []) assert.ok(mats.has(m), `숨김 재질 ${m}(${t}) 가 GLB 에 없음`);
assert.deepEqual(items.targets.jusaeso.hidden, ['sunred'], '일장기 숨김');
const list = missions.missions; assert.equal(list.length, 8, '미션 8');
const must = life.situations.filter((x) => x.must); assert.equal(must.length, 8, '꼭 나오는 상황 8(3·1 은 밤·아침 둘)'); assert.ok(life.situations.length - must.length >= life.mixedCount && life.situations.length === 16, '섞여 8 ≥ mixedCount 4');
for (const m of list) assert.ok(must.some((x) => 'sit:' + x.id + ':done' === m.done), `미션 ${m.id} 가 상황과 안 맞음`);
for (const sit of life.situations) { if (sit.place) assert.ok(world.areas[sit.place], `상황 ${sit.id} 장소 ${sit.place}`); for (const c of sit.choices) assert.ok(c.done || c.count, `상황 ${sit.id} 선택 ${c.id} 에 done 없음`); }
const blob = JSON.stringify(items) + JSON.stringify(npcDefs) + JSON.stringify(life.situations.map((s) => s.choices.map((c) => c.flag)));
for (const sit of life.situations) for (const c of sit.choices) if (c.done) for (const f of c.done.split('&&').map((x) => x.trim()).filter((x) => !x.startsWith('!'))) assert.ok(blob.includes(`"${f}"`), `상황 ${sit.id} 선택 ${c.id} 의 done 깃발 ${f} 를 세우는 곳이 없음`);
for (const sit of life.situations) for (const c of sit.choices) if (c.status) assert.ok(life.status.rules.some((r) => r.id === c.status), `상황 ${sit.id} 선택 ${c.id} 의 신분 ${c.status} 없음`);
for (const s of life.situations) if (s.onOpen) for (const a of s.onOpen) if (a.show) assert.ok(ix.includes('ix_' + a.show.name), `onOpen show ${a.show.name}`);
const last = life.situations.find((s) => s.id === 'jingyong'); for (const c of last.choices) assert.ok(c.then?.some((a) => a.end), `jingyong 선택 ${c.id} 에 끝 카드 없음`);
const toji = life.situations.find((s) => s.id === 'toji'); assert.ok(toji.onOpen?.[0]?.show?.mats?.[0] === 'sunred', '토지 조사 열릴 때 일장기');
const ids = new Set(life.status.rules.map((r) => r.id));
for (const b of last.choices[0].then[0].end.branches) for (const f of (b.if || '').match(/status:(\w+)/g) || []) assert.ok(ids.has(f.slice(7)), `끝 갈림 ${b.id} 의 ${f} 없음`);
assert.equal(last.choices[0].then[0].end.branches.length, 45, '끝 갈림 45');
assert.ok(life.grain?.open && life.rank?.open && life.carry?.from === 'joseon-late-life', '쌀 + 자리 + 조선 후기에서 넘겨받음');
const st = life.status.rules; const cap = (id) => st.find((r) => r.id === id).cap;
assert.ok(ids.size === 14 && cap('chinil') === 6 && cap('dongnip') === 0 && ['jiju', 'sangin', 'gisulja', 'nongmin', 'sojak', 'nodongja', 'yetnobi', 'yetbaekjeong', 'hwajeon', 'haksaeng', 'gyosa', 'ijumin'].every((k) => cap(k) === 4), '직업 카드 14 — 천장은 누구나 4, 협력 6, 쫓기는 몸 0');
assert.ok(st.findIndex((r) => r.id === 'chinil') < st.findIndex((r) => r.id === 'jiju') && st.at(-1).id === 'nongmin', '삶 중간 카드가 앞, 자작농이 기본');
assert.ok(st.some((r) => r.id === 'yetbaekjeong' && r.if === 'fromstatus:baekjeong') && st.some((r) => r.id === 'yetnobi' && r.if === 'fromstatus:solgeo') && st.some((r) => r.id === 'jiju' && r.if === 'fromstatus:sinyang'), '백정→옛 백정 / 솔거→옛 노비 / 공명첩 집→지주');
assert.ok(life.hurts?.wound && life.hurts?.leg && life.hurts?.jail && world.danger?.safe?.length === 8, '흔적 셋 + 밤 안전 자리 8');
assert.ok(world.hideHunger && world.hunger.perSecond === 0, '배고픔 없음');
assert.ok(world.gate?.next === 'daehan-life' && !world.gate.ready, '문 → 대한민국(준비 중)');
const prev = JSON.parse(fs.readFileSync(new URL('../eras/joseon-late-life/world.json', import.meta.url))); assert.ok(prev.gate?.next === 'gaehang-life' && prev.gate.ready, '조선 후기 끝 카드 → 개항 문(열림)');
console.log(`gaehang-life: ix ${ix.length} · areas ${areas.length} · npc ${npcs.length} · 상황 ${life.situations.length} · 직업 ${ids.size} · 끝 갈림 ${last.choices[0].then[0].end.branches.length} · glb ${(buffer.length / 1048576).toFixed(1)}MB · 노드 ${names.length}`);
