// 조선 후기 인생 층 구조 검증 — 터는 조선 전기 GLB(../joseon-life/joseon.glb)를 그대로 가리킨다 + scene.add 소품 셋(전기수·광산 굴·동학 모임). NPC 18·구역 19·미션 7·숨김 재질(관군 진영·이양선 = 전기의 청 진영·왜선 재질)·done 깃발 전수·신분 16·|| 조건
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base = new URL('../eras/joseon-late-life/', import.meta.url);
const read = (f) => JSON.parse(fs.readFileSync(new URL(f, base)));
const world = read('world.json'), items = read('items.json'), npcDefs = read('npcs.json'), missions = read('missions.json'), scene = read('scene.json'), life = read('life.json');
assert.equal(world.glb, '../joseon-life/joseon.glb', '터 = 조선 전기 GLB 그대로');
const buffer = fs.readFileSync(new URL(world.glb, base));
const data = JSON.parse(buffer.subarray(20, 20 + buffer.readUInt32LE(12)).toString());
const sceneTypes = new Set((scene.add || []).map((a) => a.name.split('_')[0]));
assert.deepEqual([...sceneTypes].sort(), ['donghak', 'jeongisu', 'mine'], 'scene.add 소품 셋');
const names = data.nodes.map((n) => n.name || '');
const ix = names.filter((n) => n.startsWith('ix_'));
const types = new Set(ix.map((n) => n.split('_')[1]));
for (const t of types) assert.ok(items.targets[t], `대상 ${t} 가 items.json 에 없음`);
for (const t of Object.keys(items.targets)) assert.ok(types.has(t) || sceneTypes.has(t), `items.json 대상 ${t} 가 GLB·scene 에 없음`);
const areas = names.filter((n) => n.startsWith('area_')).map((n) => n.slice(5));
for (const a of Object.keys(world.areas)) assert.ok(areas.includes(a), `구역 ${a} 없음`);
assert.equal(Object.keys(world.areas).length, 19, '구역 19'); assert.ok(areas.includes(world.face), `시작 시선 구역 ${world.face}`);
const npcs = ix.filter((n) => n.startsWith('ix_npc_')).map((n) => n.slice(7));
for (const id of Object.keys(npcDefs)) assert.ok(npcs.includes(id), `NPC ${id} 가 GLB 에 없음`);
for (const id of npcs) assert.ok(npcDefs[id], `GLB NPC ${id} 가 npcs.json 에 없음`);
assert.equal(npcs.length, 18, 'NPC 18(이름만 바뀜: 김만덕·정약용·홍경래·장길산·김 대감)');
assert.ok(npcDefs.jumo.name.includes('김만덕') && npcDefs.sunsin.name.includes('정약용') && npcDefs.uibyeong.name.includes('홍경래') && npcDefs.kkeokjeong.name.includes('장길산'), '인물 카드 넷');
const mats = new Set((data.materials || []).map((m) => m.name));
for (const [t, h] of Object.entries(items.targets)) for (const m of h.hidden || []) assert.ok(mats.has(m), `숨김 재질 ${m}(${t}) 가 GLB 에 없음`);
const list = missions.missions; assert.equal(list.length, 7, '미션 7');
const must = life.situations.filter((x) => x.must); assert.equal(must.length, 7, '꼭 나오는 상황 7'); assert.ok(life.situations.length - must.length >= life.mixedCount && life.situations.length === 16, '섞여 9 ≥ mixedCount 4');
for (const m of list) assert.ok(must.some((x) => 'sit:' + x.id + ':done' === m.done), `미션 ${m.id} 가 상황과 안 맞음`);
for (const sit of life.situations) { if (sit.place) assert.ok(world.areas[sit.place], `상황 ${sit.id} 장소 ${sit.place}`); for (const c of sit.choices) assert.ok(c.done || c.count, `상황 ${sit.id} 선택 ${c.id} 에 done 없음`); }
const blob = JSON.stringify(items) + JSON.stringify(npcDefs) + JSON.stringify(life.situations.map((s) => s.choices.map((c) => c.flag)));
for (const sit of life.situations) for (const c of sit.choices) if (c.done) for (const f of c.done.split('&&').map((x) => x.trim()).filter((x) => !x.startsWith('!'))) assert.ok(blob.includes(`"${f}"`), `상황 ${sit.id} 선택 ${c.id} 의 done 깃발 ${f} 를 세우는 곳이 없음`);
for (const sit of life.situations) for (const c of sit.choices) if (c.status) assert.ok(life.status.rules.some((r) => r.id === c.status), `상황 ${sit.id} 선택 ${c.id} 의 신분 ${c.status} 없음`);
for (const s of life.situations) if (s.onOpen) for (const a of s.onOpen) if (a.show) assert.ok(ix.includes('ix_' + a.show.name), `onOpen show ${a.show.name}`);
const last = life.situations.find((s) => s.id === 'uprising'); for (const c of last.choices) assert.ok(c.then?.some((a) => a.end), `uprising 선택 ${c.id} 에 끝 카드 없음`);
assert.ok(last.onOpen.length === 2, '봉기 때 관군 진영 + 이양선 보임');
// 끝 카드 갈림의 조건에 쓰인 status 가 규칙에 있는지
const ids = new Set(life.status.rules.map((r) => r.id));
for (const b of last.choices[0].then[0].end.branches) for (const f of (b.if || '').match(/status:(\w+)/g) || []) assert.ok(ids.has(f.slice(7)), `끝 갈림 ${b.id} 의 ${f} 없음`);
assert.ok(life.grain?.open && life.rank?.open && life.carry?.from === 'joseon-life', '곡식 + 벼슬 + 조선 전기에서 넘겨받음');
const st = life.status.rules; const cap = (id) => st.find((r) => r.id === id).cap;
assert.ok(ids.size === 16 && cap('yangban') === 6 && cap('mollak') === 6 && cap('seoeol') === 4 && cap('sinyang') === 4 && cap('jungin') === 3 && cap('sangmin') === 3 && cap('dogo') === 3 && cap('sojak') === 2 && cap('jangin') === 2 && cap('solgeo') === 0 && cap('oegeo') === 0 && cap('gwanno') === 0 && cap('baekjeong') === 0 && cap('hwajeon') === 0 && cap('pumpali') === 0 && cap('bandit') === 0, '신분 16 + 천장');
assert.ok(st.findIndex((r) => r.id === 'seoeol') < st.findIndex((r) => r.id === 'yangban'), '서얼 규칙이 양반보다 앞');
assert.ok(st.find((r) => r.id === 'gwanno').if === 'from:kk_caught' && st.some((r) => r.id === 'hwajeon' && r.if === 'from:rebel'), '산채로 가다 잡힘 → 관노 / 토벌 → 화전');
assert.ok(JSON.stringify(items).includes(' || '), '|| 묶음 조건 사용');
assert.ok(life.hurts?.wound && life.hurts?.leg && life.hurts?.jail && world.danger?.safe?.length === 6, '흔적 셋 + 밤 안전 자리 6(외딴 집 추가)');
assert.ok(world.hideHunger && world.hunger.perSecond === 0, '배고픔 없음');
assert.ok(world.gate?.next === 'gaehang-life' && world.gate.ready, '문 → 개항(열림)');
const prev = JSON.parse(fs.readFileSync(new URL('../eras/joseon-life/world.json', import.meta.url))); assert.ok(prev.gate?.next === 'joseon-late-life' && prev.gate.ready, '조선 전기 끝 카드 → 조선 후기 문(열림)');
console.log(`joseon-late-life: ix ${ix.length} + scene ${scene.add.length} · areas ${areas.length} · npc ${npcs.length} · 상황 ${life.situations.length} · 신분 ${ids.size} · 끝 갈림 ${last.choices[0].then[0].end.branches.length}`);
